server:
  port: 8091

# thread pool configuration
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# management configuration
dynamic:
  thread:
    pool:
      config:
        enabled: true
        # redis host
        host: 127.0.0.1
        # redis port
        port: 16379

logging:
  level:
    root: info
  config: classpath:logback-spring.xml